apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mosip
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'id-authentication'
        metrics_path: '/idauthentication/actuator/prometheus'
        static_configs:
          - targets: ['id-authentication-service:80']
        scrape_interval: 10s
      
      - job_name: 'registration'
        metrics_path: '/registration/actuator/prometheus'
        static_configs:
          - targets: ['registration-service:80']
        scrape_interval: 10s