apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-authentication
  namespace: mosip
  labels:
    app: id-authentication
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: id-authentication
  template:
    metadata:
      labels:
        app: id-authentication
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/idauthentication/actuator/prometheus"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: id-authentication
        image: mosipid/mosip-id-authentication-service:1.2.4
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SPRING_CONFIG_LOCATION
          value: "file:/app/config/"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mosip-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mosip-secrets
              key: db-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mosip-secrets
              key: redis-password
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /idauthentication/actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /idauthentication/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
      volumes:
      - name: config-volume
        configMap:
          name: id-auth-config
---
apiVersion: v1
kind: Service
metadata:
  name: id-authentication-service
  namespace: mosip
  labels:
    app: id-authentication
spec:
  selector:
    app: id-authentication
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP